// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPL9CHTDtF4W6dUMzLjcTsAJHvU8-a8LY',
    appId: '1:236558028259:web:482ea7741095de629ee4d6',
    messagingSenderId: '236558028259',
    projectId: 'capistock-1c0f1',
    authDomain: 'capistock-1c0f1.firebaseapp.com',
    storageBucket: 'capistock-1c0f1.appspot.com',
    measurementId: 'G-BGQDEHDRTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwHky9xdW6xBdSjkD-XubNLhyQo7kCFl4',
    appId: '1:236558028259:android:a85367fa62cf20469ee4d6',
    messagingSenderId: '236558028259',
    projectId: 'capistock-1c0f1',
    storageBucket: 'capistock-1c0f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcqxU7qJ3c5Dl7Rbng3ZtdKYZHsIbwyMA',
    appId: '1:236558028259:ios:a5493320c8fa12df9ee4d6',
    messagingSenderId: '236558028259',
    projectId: 'capistock-1c0f1',
    storageBucket: 'capistock-1c0f1.appspot.com',
    iosBundleId: 'com.example.capistock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcqxU7qJ3c5Dl7Rbng3ZtdKYZHsIbwyMA',
    appId: '1:236558028259:ios:a5493320c8fa12df9ee4d6',
    messagingSenderId: '236558028259',
    projectId: 'capistock-1c0f1',
    storageBucket: 'capistock-1c0f1.appspot.com',
    iosBundleId: 'com.example.capistock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPL9CHTDtF4W6dUMzLjcTsAJHvU8-a8LY',
    appId: '1:236558028259:web:34d15d243dc762649ee4d6',
    messagingSenderId: '236558028259',
    projectId: 'capistock-1c0f1',
    authDomain: 'capistock-1c0f1.firebaseapp.com',
    storageBucket: 'capistock-1c0f1.appspot.com',
    measurementId: 'G-RZXPGM437F',
  );
}
